### ISSUE TITLE
Exception thrown with comma separated mod directories

### ISSUE THREAD

**Issue by Aoldri** [Thial/StalkerModdingHelper#1]
I think this check (https://github.com/Thial/StalkerModdingHelper/blob/master/Static.cs#L66-L73) is responsible as it throws an exception since it considers the entire string as a path, instead of first splitting them by the `,`s.

Otherwise, thanks for this program! It looks pretty useful as I've got it to work with MO2 and, if this particular issue gets fixed, addons set up with a FOMOD structure.

**Comment by Thial** [comment]
Hi thanks for the report. Sorry for the late reply but I've been extremely busy with real life.
The initial version wasn't written with multiple instances in mind, more of a separate config per mod but I started working on a json based config implementation which supports multiple mods and output directories from a single config file and should be fully compatible with MO2 as well.
